In [5]:
import pandas as pd
train = pd.read_csv('train.csv')
submission = pd.read_csv('sample_submission.csv')

In [6]:
import matplotlib.pyplot as plt

In [7]:
train.head()

           일시  최고기온  최저기온   일교차  강수량  평균습도  평균풍속  일조합  일사합  일조율  평균기온
0  1960-01-01   2.2  -5.2   7.4  NaN  68.3   1.7  6.7  NaN  NaN  -1.6
1  1960-01-02   1.2  -5.6   6.8  0.4  87.7   1.3  0.0  NaN  NaN  -1.9
2  1960-01-03   8.7  -2.1  10.8  0.0  81.3   3.0  0.0  NaN  NaN   4.0
3  1960-01-04  10.8   1.2   9.6  0.0  79.7   4.4  2.6  NaN  NaN   7.5
4  1960-01-05   1.3  -8.2   9.5  NaN  44.0   5.1  8.2  NaN  NaN  -4.6

In [8]:
train.describe()

,최고기온,최저기온,일교차,강수량,평균습도,평균풍속,일조합,일사합,일조율,평균기온
count,23008.000000,23008.000000,23007.000000,9150.000000,23011.000000,23007.000000,22893.000000,18149.000000,22645.000000,23011.000000
mean,17.071714,8.451960,8.619277,9.593683,65.202851,2.380993,5.858826,11.933170,48.653526,12.415419
std,10.714471,10.578285,2.907096,21.966135,14.549077,0.947595,3.816941,6.419122,31.662321,10.489515
min,-13.600000,-20.200000,1.000000,0.000000,17.900000,0.100000,0.000000,0.000000,0.000000,-16.400000
25%,7.800000,-0.300000,6.600000,0.100000,54.900000,1.700000,2.200000,7.000000,17.800000,3.400000
50%,18.900000,9.200000,8.600000,1.400000,65.500000,2.200000,6.600000,11.220000,55.700000,13.800000
75%,26.400000,17.900000,10.600000,8.500000,75.800000,2.900000,9.000000,16.620000,78.000000,21.800000
max,39.600000,30.300000,19.600000,332.800000,99.800000,7.800000,13.700000,33.480000,96.900000,33.700000

In [9]:
# '일시' 열을 datetime 형식으로 변환
train['일시'] = pd.to_datetime(train['일시'])

# 연도, 월, 일 열 생성
train['연도'] = train['일시'].dt.year
train['월'] = train['일시'].dt.month
train['일'] = train['일시'].dt.day

# '일시' 열을 datetime 형식으로 변환
submission['일시'] = pd.to_datetime(submission['일시'])

# 연도, 월, 일 열 생성
submission['연도'] = submission['일시'].dt.year
submission['월'] = submission['일시'].dt.month
submission['일'] = submission['일시'].dt.day

In [10]:
import pandas as pd

# '일시' 열을 datetime 형식으로 변환
train['일시'] = pd.to_datetime(train['일시'])

# '일시' 열에서 주차 정보 추출
train['주차'] = train['일시'].dt.isocalendar().week

# 결과 확인
print(train[['일시', '주차']])

# '일시' 열을 datetime 형식으로 변환
submission['일시'] = pd.to_datetime(submission['일시'])

# '일시' 열에서 주차 정보 추출
submission['주차'] = submission['일시'].dt.isocalendar().week

# 결과 확인
print(submission[['일시', '주차']])

              일시  주차
0     1960-01-01  53
1     1960-01-02  53
2     1960-01-03  53
3     1960-01-04   1
4     1960-01-05   1
...          ...  ..
23006 2022-12-27  52
23007 2022-12-28  52
23008 2022-12-29  52
23009 2022-12-30  52
23010 2022-12-31  52

[23011 rows x 2 columns]
            일시  주차
0   2023-01-01  52
1   2023-01-02   1
2   2023-01-03   1
3   2023-01-04   1
4   2023-01-05   1
..         ...  ..
353 2023-12-20  51
354 2023-12-21  51
355 2023-12-22  51
356 2023-12-23  51
357 2023-12-24  51

[358 rows x 2 columns]

In [11]:
# 결측치 확인
missing_values = train.isnull()

# 각 열별로 결측치 개수 세기
missing_count_per_column = missing_values.sum()

# 결과 출력
print(missing_count_per_column)

일시          0
최고기온        3
최저기온        3
일교차         4
강수량     13861
평균습도        0
평균풍속        4
일조합       118
일사합      4862
일조율       366
평균기온        0
연도          0
월           0
일           0
주차          0
dtype: int64

In [12]:
# '일시' 열을 datetime 형식으로 변환
train['일시'] = pd.to_datetime(train['일시'])

# '일시' 열에서 날짜만 추출하여 '년도-월-일' 형식으로 저장
train['날짜'] = train['일시'].dt.strftime('%Y-%m-%d')

# '날짜' 열을 datetime 형식으로 변환
train['날짜'] = pd.to_datetime(train['날짜'])

# '날짜' 열에서 1년 중 몇 번째 날인지 추출
train['년중_일수'] = (train['날짜'] - pd.to_datetime(train['날짜'].dt.year, format='%Y')).dt.days + 1

# 결과 확인
print(train[['일시', '주차', '년중_일수']])



# '일시' 열을 datetime 형식으로 변환
submission['일시'] = pd.to_datetime(submission['일시'])

# '일시' 열에서 날짜만 추출하여 '년도-월-일' 형식으로 저장
submission['날짜'] = submission['일시'].dt.strftime('%Y-%m-%d')

# '날짜' 열을 datetime 형식으로 변환
submission['날짜'] = pd.to_datetime(submission['날짜'])

# '날짜' 열에서 1년 중 몇 번째 날인지 추출
submission['년중_일수'] = (submission['날짜'] - pd.to_datetime(submission['날짜'].dt.year, format='%Y')).dt.days + 1

# 결과 확인
print(submission[['일시', '주차', '년중_일수']])

              일시  주차  년중_일수
0     1960-01-01  53      1
1     1960-01-02  53      2
2     1960-01-03  53      3
3     1960-01-04   1      4
4     1960-01-05   1      5
...          ...  ..    ...
23006 2022-12-27  52    361
23007 2022-12-28  52    362
23008 2022-12-29  52    363
23009 2022-12-30  52    364
23010 2022-12-31  52    365

[23011 rows x 3 columns]
            일시  주차  년중_일수
0   2023-01-01  52      1
1   2023-01-02   1      2
2   2023-01-03   1      3
3   2023-01-04   1      4
4   2023-01-05   1      5
..         ...  ..    ...
353 2023-12-20  51    354
354 2023-12-21  51    355
355 2023-12-22  51    356
356 2023-12-23  51    357
357 2023-12-24  51    358

[358 rows x 3 columns]

In [13]:
# 계절 변수 생성
train['계절'] = ''

for i, month in enumerate(train['월']):
    if 3 <= month <= 5:
        train.at[i, '계절'] = '봄'
    elif 6 <= month <= 8:
        train.at[i, '계절'] = '여름'
    elif 9 <= month <= 11:
        train.at[i, '계절'] = '가을'
    else:
        train.at[i, '계절'] = '겨울'

# 결과 확인
print(train[['일시', '월', '계절']])


# 계절 변수 생성
submission['계절'] = ''

for i, month in enumerate(submission['월']):
    if 3 <= month <= 5:
        submission.at[i, '계절'] = '봄'
    elif 6 <= month <= 8:
        submission.at[i, '계절'] = '여름'
    elif 9 <= month <= 11:
        submission.at[i, '계절'] = '가을'
    else:
        submission.at[i, '계절'] = '겨울'

# 결과 확인
print(submission[['일시', '월', '계절']])

              일시   월  계절
0     1960-01-01   1  겨울
1     1960-01-02   1  겨울
2     1960-01-03   1  겨울
3     1960-01-04   1  겨울
4     1960-01-05   1  겨울
...          ...  ..  ..
23006 2022-12-27  12  겨울
23007 2022-12-28  12  겨울
23008 2022-12-29  12  겨울
23009 2022-12-30  12  겨울
23010 2022-12-31  12  겨울

[23011 rows x 3 columns]
            일시   월  계절
0   2023-01-01   1  겨울
1   2023-01-02   1  겨울
2   2023-01-03   1  겨울
3   2023-01-04   1  겨울
4   2023-01-05   1  겨울
..         ...  ..  ..
353 2023-12-20  12  겨울
354 2023-12-21  12  겨울
355 2023-12-22  12  겨울
356 2023-12-23  12  겨울
357 2023-12-24  12  겨울

[358 rows x 3 columns]

In [14]:
# '계절' 열에 대한 원핫인코딩 수행
one_hot_encoded = pd.get_dummies(train['계절'], prefix='계절')

# 기존 데이터프레임과 합치기
train = pd.concat([train, one_hot_encoded], axis=1)

# '계절' 열과 중복된 열 삭제
train.drop(['계절'], axis=1, inplace=True)

# 결과 확인
print(train)


# '계절' 열에 대한 원핫인코딩 수행
one_hot_encoded = pd.get_dummies(submission['계절'], prefix='계절')

# 기존 데이터프레임과 합치기
submission = pd.concat([submission, one_hot_encoded], axis=1)

# '계절' 열과 중복된 열 삭제
submission.drop(['계절'], axis=1, inplace=True)

# 결과 확인
print(train)
print(submission)

              일시  최고기온  최저기온   일교차  강수량  평균습도  평균풍속  일조합    일사합   일조율  ...  \
0     1960-01-01   2.2  -5.2   7.4  NaN  68.3   1.7  6.7    NaN   NaN  ...
1     1960-01-02   1.2  -5.6   6.8  0.4  87.7   1.3  0.0    NaN   NaN  ...
2     1960-01-03   8.7  -2.1  10.8  0.0  81.3   3.0  0.0    NaN   NaN  ...
3     1960-01-04  10.8   1.2   9.6  0.0  79.7   4.4  2.6    NaN   NaN  ...
4     1960-01-05   1.3  -8.2   9.5  NaN  44.0   5.1  8.2    NaN   NaN  ...
...          ...   ...   ...   ...  ...   ...   ...  ...    ...   ...  ...
23006 2022-12-27   3.3  -7.3  10.6  NaN  69.8   1.8  8.8  10.25  91.7  ...
23007 2022-12-28   0.1  -6.0   6.1  0.1  58.1   2.5  8.7  10.86  90.6  ...
23008 2022-12-29   2.1  -7.8   9.9  0.0  56.3   1.7  9.0  10.88  93.8  ...
23009 2022-12-30   2.3  -4.4   6.7  0.0  65.6   1.9  7.9  10.84  82.3  ...
23010 2022-12-31   2.1  -5.1   7.2  0.0  65.5   1.4  1.1   4.16  11.5  ...

         연도   월   일  주차         날짜 년중_일수  계절_가을  계절_겨울   계절_봄  계절_여름
0      1960   1   1  53 1960-01-01     1  False   True  False  False
1      1960   1   2  53 1960-01-02     2  False   True  False  False
2      1960   1   3  53 1960-01-03     3  False   True  False  False
3      1960   1   4   1 1960-01-04     4  False   True  False  False
4      1960   1   5   1 1960-01-05     5  False   True  False  False
...     ...  ..  ..  ..        ...   ...    ...    ...    ...    ...
23006  2022  12  27  52 2022-12-27   361  False   True  False  False
23007  2022  12  28  52 2022-12-28   362  False   True  False  False
23008  2022  12  29  52 2022-12-29   363  False   True  False  False
23009  2022  12  30  52 2022-12-30   364  False   True  False  False
23010  2022  12  31  52 2022-12-31   365  False   True  False  False

[23011 rows x 21 columns]
              일시  최고기온  최저기온   일교차  강수량  평균습도  평균풍속  일조합    일사합   일조율  ...  \
0     1960-01-01   2.2  -5.2   7.4  NaN  68.3   1.7  6.7    NaN   NaN  ...
1     1960-01-02   1.2  -5.6   6.8  0.4  87.7   1.3  0.0    NaN   NaN  ...
2     1960-01-03   8.7  -2.1  10.8  0.0  81.3   3.0  0.0    NaN   NaN  ...
3     1960-01-04  10.8   1.2   9.6  0.0  79.7   4.4  2.6    NaN   NaN  ...
4     1960-01-05   1.3  -8.2   9.5  NaN  44.0   5.1  8.2    NaN   NaN  ...
...          ...   ...   ...   ...  ...   ...   ...  ...    ...   ...  ...
23006 2022-12-27   3.3  -7.3  10.6  NaN  69.8   1.8  8.8  10.25  91.7  ...
23007 2022-12-28   0.1  -6.0   6.1  0.1  58.1   2.5  8.7  10.86  90.6  ...
23008 2022-12-29   2.1  -7.8   9.9  0.0  56.3   1.7  9.0  10.88  93.8  ...
23009 2022-12-30   2.3  -4.4   6.7  0.0  65.6   1.9  7.9  10.84  82.3  ...
23010 2022-12-31   2.1  -5.1   7.2  0.0  65.5   1.4  1.1   4.16  11.5  ...

         연도   월   일  주차         날짜 년중_일수  계절_가을  계절_겨울   계절_봄  계절_여름
0      1960   1   1  53 1960-01-01     1  False   True  False  False
1      1960   1   2  53 1960-01-02     2  False   True  False  False
2      1960   1   3  53 1960-01-03     3  False   True  False  False
3      1960   1   4   1 1960-01-04     4  False   True  False  False
4      1960   1   5   1 1960-01-05     5  False   True  False  False
...     ...  ..  ..  ..        ...   ...    ...    ...    ...    ...
23006  2022  12  27  52 2022-12-27   361  False   True  False  False
23007  2022  12  28  52 2022-12-28   362  False   True  False  False
23008  2022  12  29  52 2022-12-29   363  False   True  False  False
23009  2022  12  30  52 2022-12-30   364  False   True  False  False
23010  2022  12  31  52 2022-12-31   365  False   True  False  False

[23011 rows x 21 columns]
            일시  평균기온    연도   월   일  주차         날짜  년중_일수  계절_가을  계절_겨울   계절_봄  \
0   2023-01-01     0  2023   1   1  52 2023-01-01      1  False   True  False
1   2023-01-02     0  2023   1   2   1 2023-01-02      2  False   True  False
2   2023-01-03     0  2023   1   3   1 2023-01-03      3  False   True  False
3   2023-01-04     0  2023   1   4   1 2023-01-04      4  False   True  False
4   2023-01-05     0  2023   1   5   1 2023-01-05      5  False   True  False
..         ...   ...   ...  ..  ..  ..        ...    ...    ...    ...    ...
353 2023-12-20     0  2023  12  20  51 2023-12-20    354  False   True  False
354 2023-12-21     0  2023  12  21  51 2023-12-21    355  False   True  False
355 2023-12-22     0  2023  12  22  51 2023-12-22    356  False   True  False
356 2023-12-23     0  2023  12  23  51 2023-12-23    357  False   True  False
357 2023-12-24     0  2023  12  24  51 2023-12-24    358  False   True  False

     계절_여름
0    False
1    False
2    False
3    False
4    False
..     ...
353  False
354  False
355  False
356  False
357  False

[358 rows x 12 columns]

In [15]:
train.head()

,일시,최고기온,최저기온,일교차,강수량,평균습도,평균풍속,일조합,일사합,일조율,...,연도,월,일,주차,날짜,년중_일수,계절_가을,계절_겨울,계절_봄,계절_여름
0,1960-01-01,2.2,-5.2,7.4,NaN,68.3,1.7,6.7,NaN,NaN,...,1960,1,1,53,1960-01-01,1,False,True,False,False
1,1960-01-02,1.2,-5.6,6.8,0.4,87.7,1.3,0.0,NaN,NaN,...,1960,1,2,53,1960-01-02,2,False,True,False,False
2,1960-01-03,8.7,-2.1,10.8,0.0,81.3,3.0,0.0,NaN,NaN,...,1960,1,3,53,1960-01-03,3,False,True,False,False
3,1960-01-04,10.8,1.2,9.6,0.0,79.7,4.4,2.6,NaN,NaN,...,1960,1,4,1,1960-01-04,4,False,True,False,False
4,1960-01-05,1.3,-8.2,9.5,NaN,44.0,5.1,8.2,NaN,NaN,...,1960,1,5,1,1960-01-05,5,False,True,False,False

-사용할 변수는 연도,월,일,주차,년중_일수,계절_가을,계절_겨울,계절_봄,계절_여름 // 총 9개이다.

In [16]:
submission.head()

,일시,평균기온,연도,월,일,주차,날짜,년중_일수,계절_가을,계절_겨울,계절_봄,계절_여름
0,2023-01-01,0,2023,1,1,52,2023-01-01,1,False,True,False,False
1,2023-01-02,0,2023,1,2,1,2023-01-02,2,False,True,False,False
2,2023-01-03,0,2023,1,3,1,2023-01-03,3,False,True,False,False
3,2023-01-04,0,2023,1,4,1,2023-01-04,4,False,True,False,False
4,2023-01-05,0,2023,1,5,1,2023-01-05,5,False,True,False,False

In [17]:
import optuna
import catboost
from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import xgboost
from xgboost import XGBRegressor

In [18]:
import sklearn
from sklearn.ensemble import VotingRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error

In [19]:
import optuna
from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# 필요한 변수 선택 (예시로 선택된 변수들이므로 실제로 사용하는 변수에 맞게 수정 필요)
selected_features = ['연도', '월', '일', '주차', '년중_일수', '계절_가을', '계절_겨울', '계절_봄', '계절_여름']
target_variable = '평균기온'

# 선택된 변수들을 사용하여 훈련 데이터셋 준비
X_train = train[selected_features]
y_train = train[target_variable]

# # 모델 정의
cat = CatBoostRegressor(random_state = 2024, 
                            n_estimators = 1000, 
                            learning_rate = 0.01, 
                            depth = 10,
                            l2_leaf_reg = 3,
                            metric_period = 1000)

xgb = XGBRegressor(n_estimators = 1000, random_state = 2024, learning_rate = 0.01, max_depth = 10)


# voting
vote_model = VotingRegressor(
    estimators =[("cat",cat), ("xgb", xgb)]
)
# 모델 학습
vote_model.fit(X_train, y_train)

0:	learn: 10.3977907	total: 153ms	remaining: 2m 32s
999:	learn: 2.9660630	total: 9.77s	remaining: 0us

VotingRegressor(estimators=[('cat',
                             <catboost.core.CatBoostRegressor object at 0x000002EA096C3E10>),
                            ('xgb',
                             XGBRegressor(base_score=None, booster=None,
                                          callbacks=None,
                                          colsample_bylevel=None,
                                          colsample_bynode=None,
                                          colsample_bytree=None, device=None,
                                          early_stopping_rounds=None,
                                          enable_categorical=False,
                                          eval_metric=None, feature_types=None,
                                          gamma=None, grow_policy=None,
                                          importance_type=None,
                                          interaction_constraints=None,
                                          learning_rate=0.01, max_bin=None,
                                          max_cat_threshold=None,
                                          max_cat_to_onehot=None,
                                          max_delta_step=None, max_depth=10,
                                          max_leaves=None,
                                          min_child_weight=None, missing=nan,
                                          monotone_constraints=None,
                                          multi_strategy=None,
                                          n_estimators=1000, n_jobs=None,
                                          num_parallel_tree=None,
                                          random_state=2024, ...))])

In [20]:
# submission 데이터에서 필요한 변수만 남기기 (평균기온을 예측하기 위한 변수)
submission_data = submission[['연도', '월', '일', '주차', '년중_일수', '계절_가을', '계절_겨울', '계절_봄', '계절_여름']]

# 예측 수행
submission_pred = vote_model.predict(submission_data)

In [21]:
submission = pd.read_csv('sample_submission.csv')
submission['평균기온']=submission_pred

In [22]:
submission.to_csv('./votemodel1.csv', index=False)